// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StdFrase.Api.Data;

#nullable disable

namespace StdFrase.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251001152029_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("StdFrase.Api.Data.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MoId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlowId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("StdFrase.Api.Data.Cuesta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Cuestas");
                });

            modelBuilder.Entity("StdFrase.Api.Data.Field", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CuestaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FieldOrder")
                        .HasColumnType("INTEGER");

                    b.Property<short>("FieldType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StandardPhrase")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("CuestaId");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("StdFrase.Api.Data.Flow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sks")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Flows");
                });

            modelBuilder.Entity("StdFrase.Api.Data.Activity", b =>
                {
                    b.HasOne("StdFrase.Api.Data.Flow", "Flow")
                        .WithMany("Activities")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flow");
                });

            modelBuilder.Entity("StdFrase.Api.Data.Field", b =>
                {
                    b.HasOne("StdFrase.Api.Data.Activity", "Activity")
                        .WithMany("Fields")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StdFrase.Api.Data.Cuesta", "Cuesta")
                        .WithMany()
                        .HasForeignKey("CuestaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Cuesta");
                });

            modelBuilder.Entity("StdFrase.Api.Data.Activity", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("StdFrase.Api.Data.Flow", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
